### ISSUE TITLE
Op inventory glitch

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/GameModeInventories#1]
Op users have their inventory reset to the last time they slept whenever they die

**Comment by eccentricdevotion** [comment]
What do you expect should happen?

**Comment by ccattell** [comment]
shouldnt they have the items that they died with?

**Comment by eccentricdevotion** [comment]
Is it because they respawn with a different gamemode than when they died?

**Comment by ccattell** [comment]
not sure ill ask if he remembers

**Comment by eccentricdevotion** [comment]
And is `save_on_death: true` in the config?

**Comment by ccattell** [comment]
yes it is true

**Comment by ccattell** [comment]
and no, he was in survival when he died, and we spawn in survival

**Comment by eccentricdevotion** [comment]
Can't seem to reproduce this on my server.
What I did:

1. `/gamemode survival eccentric_nz`
2. `/time set night`
3. slept in bed
4. moved and added new items to my inventory
5. `/kill eccentric_nz`
6. respawned

Inventory contents were restored to the same as when I died.

Plugin conflict?

**Comment by ccattell** [comment]
it must be... i will research it more and get back with you
