### ISSUE TITLE
Falling blocks not dropping items

### ISSUE THREAD

**Issue by Nety01** [eccentricdevotion/GameModeInventories#10]
Hey, sorry if I have just misconfigured it, I'm maybe just lost in the configuration - the config options like no_drops etc. apply only to people with creative mode (and with no bypass) right?

Anyway my problem is, when in creative or survival mode place a sand above torch and the block does break, it doesn't drop a item.

Using Paper 1.15.2 and GMI #137
Config.yml: https://gist.github.com/Nety01/ce2d8c4aaf126299785fdbe7d64529d4

**Comment by eccentricdevotion** [comment]
`no_falling_drops` is irrespective of gamemode and doesn't have a bypass

**Comment by Nety01** [comment]
Ok thanks
