### ISSUE TITLE
SpawnEggs on blacklist still usable for non op without bypass permission

### ISSUE THREAD

**Issue by H3adcode** [eccentricdevotion/GameModeInventories#11]
Hello, as follow-up to some comments stating that eggs and spawn eggs are still usable although they are on the blacklist I experience the same issue.

- I do not have op status
- I do not have the bypass or bypass.blacklist permission (using luckperms)
- I can use/throw eggs and spawn eggs

As a comparison, TNT and other blocks cannot be placed or dropped as expected. If I gain the bypass permission, I can, that is working.

config.yaml
```
creative_blacklist: true
blacklist:
- CHICKEN_SPAWN_EGG
- CREEPER_SPAWN_EGG
- EGG
- TNT
```
```
bypass:
  inventories: true
  items: true
  blacklist: true
  survival: false
  commands: false
  trades: false
```
luckperms permission check
```
> lp group default permission check gamemodeinventories.bypass
[14:12:03 INFO]: [LP] default has permission gamemodeinventories.bypass set to undefined in context global.
> lp group default permission check gamemodeinventories.bypass.blacklist
[14:12:15 INFO]: [LP] default has permission gamemodeinventories.bypass.blacklist set to undefined in context global.
```

Greetings,
H3adless

complete config:
[config.txt](https://github.com/eccentricdevotion/GameModeInventories/files/4695398/config.txt)

**Comment by eccentricdevotion** [comment]
Cannot reproduce using your config, no op, no perms.
Have you tried updating? http://tardisjenkins.duckdns.org:8080/job/GameModeInventories/

**Comment by H3adcode** [comment]
I made a minimal test case with a clean server (Craftbukkit-1.15.2.jar and Spigot-1.15.2.jar tested), plugin version #137. No other Server Plugins. Vanilla Java 1.15.2 client. Running on Windows 10. Edited permission.yml to include for all players (no other permissions): 
```
minecraft.command.gamemode: true
```
The same GMI config as provided above. The issue remains. Blocks are handled correctly. Using/throwing eggs still possible.

**Comment by eccentricdevotion** [comment]
OK, can reproduce now, I'll see what's up...

**Comment by eccentricdevotion** [comment]
Try build 138 http://tardisjenkins.duckdns.org:8080/job/GameModeInventories/

**Comment by H3adcode** [comment]
Works on test case and online server. As of build #138, all eggs on the blacklist can no longer be used nor thrown. Great work.
