### ISSUE TITLE
TIMING_STACK_CORRUPTION Error

### ISSUE THREAD

**Issue by TheNety** [eccentricdevotion/GameModeInventories#12]
Hey, got this console error https://pastebin.com/U9vsdVUV

Paper 1.15.2
GameModeInventories 3.3.1

**Comment by eccentricdevotion** [comment]
From the paste:
`Look for errors above this in the logs`

Are there any errors?

**Comment by Nety01** [comment]
No, there are only these same errors repeating. Checked whole log from server start.

**Comment by eccentricdevotion** [comment]
Try latest build (139) might make a difference, hard to say...

**Comment by Nety01** [comment]
Will try thank you, it's pretty rare error, saw it firstly today so I think we can consider this as closed for now, if it's not a plugin breaking issue.
