### ISSUE TITLE
error every time change game mode  

### ISSUE THREAD

**Issue by progamer562** [eccentricdevotion/GameModeInventories#15]
i get this 
Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v2.3.2

**Comment by eccentricdevotion** [comment]
Need to see the whole error from the log, but seems like a perworldinventory issue to me...

**Comment by progamer562** [comment]
Never mind I removed the plug-in from the server


Btw I miss going to your class after school

**Comment by eccentricdevotion** [comment]
Yep, probably best not to ru two plugins that try to control inventories, there are bound to be some conflicts...

Hopefully classes will be able to be run again soon :)

**Comment by progamer562** [comment]
i dont go to to that school any more tho
