### ISSUE TITLE
Error The skull profile is missing a name or textures!

### ISSUE THREAD

**Issue by iOshawott** [eccentricdevotion/GameModeInventories#17]
https://pastebin.com/z81qi442

I have a playerdata file with skull that did that error if needed.

After this error inventory of player has been resetted, backup was needed for recovery.

**Comment by eccentricdevotion** [comment]
I cannot reproduce this with a valid skull/player head. Changing gamemodes and back again restores the skull as expected.
How is the skull being given to the player?
Perhaps attaching the playerdata file might help see what the issue is.

**Comment by iOshawott** [comment]
Reproduction steps:
(issue is because conflict HeadDatabase with CoreProtect)

1. Take some heads from HeadDatabase [http://minecraft-heads.com/]
2. Place that head
3. Destroy that head
4. "Rollback" that head with coreprotect
5. Rolled back head is Steve/Alex without skin
6. Pickuping it, having in inventory and changing gamemode - error & inventory clear

I didn't knew where upload, so it's here (if still needed - .dat file) https://easyupload.io/ghiax1

**Comment by eccentricdevotion** [comment]
I have fixed the issue of GMI not being able to read the corrupted skull data. Before saving the inventory it will check for corrupt player heads, and if found, will strip away the skull meta leaving just a plain Steve/Alex head.

Get the latest JAR here: http://tardisjenkins.duckdns.org:8080/job/GameModeInventories/

Nothing I can do about the underlying problem of CoreProtect not rolling back playerheads correctly, I suggest you raise a ticket with the plugin author(s) if you haven't done so already.

**Comment by eccentricdevotion** [comment]
https://github.com/PlayPro/CoreProtect/issues/70
