### ISSUE TITLE
Plugin sometimes freezes then kills itself and everything with it

### ISSUE THREAD

**Issue by JasonHorkles** [eccentricdevotion/GameModeInventories#3]
On Paper-33 1.15.1 version 3.2.1 the plugin doesn't seem to like something. Any way to fix this or is it a bug? https://hasteb.in/vevaqako.log
Used to happen on version 3.2 as well

**Comment by eccentricdevotion** [comment]
Looks like it is struggling to read / write to the SQLite database, corrupt file?

**Comment by JasonHorkles** [comment]
Is there a way to fix it without losing peoples' inventories?

**Comment by eccentricdevotion** [comment]
Not that I know of, but I'm not 100% sure what the issue is anyway...

**Comment by JasonHorkles** [comment]
I asked in the Paper server a while ago and they were saying it was trying to open multiple sqlite connections on multiple threads and then all heck broke loose after that

**Comment by eccentricdevotion** [comment]
GMI uses a singleton to connect to SQLite i.e. only one connection instance should ever be initiated. Are you reloading the server instead of stopping and restarting?

**Comment by eccentricdevotion** [comment]
The GameModeInventoriesSQLiteConnection.java file hasn't really changed apart from formatting issues  since 2015...

**Comment by JasonHorkles** [comment]
Nope I never reload
In fact the error seems to be more likely to occur after startup

**Comment by eccentricdevotion** [comment]
Is
```
track_creative_place:
  enabled: true
```
?
If it is you should really be using MySQL as there are likely to be millions of records of creative block placements which are loaded at startup. SQLite will struggle with that.
Can you attach your DB file?

**Comment by JasonHorkles** [comment]
Oh yeah it's set to true. What does it do anyways?
https://1drv.ms/u/s!ArOS099NaR9Lhvcs3cZqXMB9uu3a3w

**Comment by eccentricdevotion** [comment]
`track_creative_place` tracks the placement of CREATIVE gamemode placed blocks, then either: disables them from being broken, or, allows them to be broken but not drop anything - and also prevents pistons from moving them and denies the block dropping if the attached block is broken.
If you don't use those features, it shouldn't be enabled...

**Comment by JasonHorkles** [comment]
Yeah I only have creative enabled in the plot world and PlotSquared should handle that so I'll just go ahead and disable it

**Comment by eccentricdevotion** [comment]
Let me know if that makes a difference.

**Comment by JasonHorkles** [comment]
Will do

**Comment by JasonHorkles** [comment]
I could also connect the plugin to a MySQL database, would that help server performance too?

**Comment by eccentricdevotion** [comment]
Probably, but you'd have to convert existing records over manually

**Comment by JasonHorkles** [comment]
Oof I'll probably just leave that as is for now

**Comment by JasonHorkles** [comment]
I'll just go ahead and close this for now but if the issue occurs again then I'll reopen it
