### ISSUE TITLE
Using another plugin "RPGChests" and switching inventories breaks the plugin

### ISSUE THREAD

**Issue by Syrkulous** [eccentricdevotion/GameModeInventories#5]
Whenever a player that has RPGChest (Premium) keys switches their game mode, that has restricted item access, and switch back. Their keys no longer stack and keep their data. Any trades for them also fail for another plugin "Shopkeepers" (but I know you have no control over that, its only the data switching after game mode changing.

This only happens when a game mode is switched from. if a player stays in survival and collects the keys, the keys never seem to break

**Comment by eccentricdevotion** [comment]
What do you mean by "restricted item access"?
What config options do you have set?

**Comment by Syrkulous** [comment]
Restricted item access as in, items can't be dropped or a select few can't be used from creative

Here is my current config
https://pastebin.com/pj7FNB1K

**Comment by eccentricdevotion** [comment]
I don't have the premium RPGChests plugin to test with, but I have raised a ticket with the author of the plugin recently due to another report - https://github.com/spigot-gillesm/RPGChest-Premium/issues/18
I can make keys with the same attributes as the plugin (using the same code as the RPGChests plugin), and GMI switches inventories just fine with them - the keys combine into the same stack after inventories have been switched. I'm currently using your config to do this.
What data is being removed from the items?
Can you supply a screenshot of the items before and after switching gamemodes?

**Comment by eccentricdevotion** [comment]
Can you supply the key config settings from the RPGChests plugin as well?

**Comment by Syrkulous** [comment]
Pastebin for RPGChest keys (There's not a config to really configure for premium)
https://pastebin.com/CzwQHRxK

I don't think any other plugin I have affects any item stacks

**Comment by eccentricdevotion** [comment]
Screenshots?

**Comment by Syrkulous** [comment]
Trying to find a good example of the issue, apologies

**Comment by Syrkulous** [comment]
This picture shows that the items wont stack together:
https://cdn.discordapp.com/attachments/204027110950436864/688535923142557762/2020-03-14_16.53.55.png

These pictures are both of the items picked up, unstacked, with same date:
https://cdn.discordapp.com/attachments/204027110950436864/688535832726208516/2020-03-14_16.54.24.png
https://cdn.discordapp.com/attachments/204027110950436864/688535834856914964/2020-03-14_16.54.25.png

This is the best I got so far

**Comment by eccentricdevotion** [comment]
Have been playing for a couple of hours now, and have switched gamemodes at least 25 times, my "keys" still stack together...

**Comment by eccentricdevotion** [comment]
Perhaps you could use an NBT editor to view the item and see what the difference between them actually is.

**Comment by Syrkulous** [comment]
Is it possible a plugin like this could cause it?
https://www.spigotmc.org/resources/creative-nbt-copy-control.13598/

**Comment by eccentricdevotion** [comment]
Possibly, but I guess you'd have to be using the middle mouse click on chests that contained the keys?
From your screenshots, the non-stackable keys still seem to have NBT data...

**Comment by eccentricdevotion** [comment]
OK, I can reproduce it with that plugin installed.
I''l do some digging and see if I can find the cause.

**Comment by eccentricdevotion** [comment]
Found what the difference is, something is adding the color formatting code for black text `§0`
![diff](https://user-images.githubusercontent.com/1841924/76723176-456c1080-67ab-11ea-80b8-c1c41296fa8a.png)

**Comment by eccentricdevotion** [comment]
GMI doesn't have any code that changes the lore of an item and the plugin only uses color formatting in its messages.

**Comment by Syrkulous** [comment]
How would I fix that issue?

**Comment by eccentricdevotion** [comment]
Actually something is stripping the color formatting because that's what you have in your config...
Perhaps try using `' '` (two single quotes with a space in between) instead of the color format `§0`?

**Comment by Syrkulous** [comment]
so should i not do a format or use ' ', I don't really understand

**Comment by eccentricdevotion** [comment]
_Don't_ use the format code for blank lines

**Comment by Syrkulous** [comment]
So no spacing out lore, or is there another way I can space out lore from enchants or item name

**Comment by eccentricdevotion** [comment]
You can still have a line in between lore and name, just put a space `' '` on the line so nothing shows.
