### ISSUE TITLE
Allow to configure mySQL table name/prefix

### ISSUE THREAD

**Issue by njuro** [eccentricdevotion/GameModeInventories#7]
Hello,

I started using this plugin with mySQL database as storage system. However, I like to have all my plugins data in single database, therefore it would be nice if it the plugin would allow to configure common prefix for table names, so they can be easily distinguishable from tables of other plugins. E.g. table "block" would become "gmi_blocks" or similiar. Would it be possible?

Thanks.

**Comment by eccentricdevotion** [comment]
6a23e2a
Build 134 or higher from here: http://tardisjenkins.duckdns.org:8080/job/GameModeInventories/

**Comment by njuro** [comment]
That was quick, thank you :)
